n = int(input())
novaLista = []
lista = (input())
lista = lista.split(' ')
lista = list(map(int, lista))
for j in range(len(lista)-1,-1,-1):
    novaLista.append(lista[j])
novaLista = str(novaLista).strip('[]').replace(',', '')
print(novaLista)
ultimo = len(lista) 
lista.insert(ultimo,lista[0])
del(lista[0])
novaLista = str(lista).strip('[]').replace(',', '')
print(novaLista)
lista.sort(reverse=True)
novaLista = str(lista).strip('[]').replace(',', '')
print(novaLista)
